service:
  type: NodePort
  nodePorts:
    http: 30069

image:
  registry: docker.io
  repository: bitnamicharts/odoo

persistence:
  enabled: false

postgresql:
  enabled: true

  primary:
    persistence:
      enabled: false